[build]
  command = "node tools/build_runtime_release.mjs"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/web-runner/"
  status = 301

[[redirects]]
  from = "/web-runner"
  to = "/web-runner/"
  status = 301

[[headers]]
  for = "/web-runner/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/web-runner/assets/gems/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/web-runner/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/web-runner/assets/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=86400"
