const test=require('node:test'),assert=require('node:assert/strict');
const {resolveSkill,turnStart}=require('../web-runner/src/core/combatRules.mjs');
const {advanceFlowOrbs,dropEnemyFlowOrbs}=require('../web-runner/src/core/flowOrbs.mjs');
const {FLOW_ORB_TUNING:T}=require('../web-runner/src/core/heroDefinitions.mjs');
const actor=(uid,kind='hero',flowMode='Warrior')=>({uid,kind,flowMode,hp:100,maxHP:100,sp:80,spMax:100,flow:0,statuses:[],stats:{SPD:10,MAG:10}});
function battle(mode='Warrior'){const hero=actor(1,'hero',mode),ally=actor(2),enemy=actor(3,'enemy');const ctx={actors:[hero,ally,enemy],state:{time:0,CombatSessionId:1},random:()=>.2,flowRandom:()=>0,calculateDamage:()=>10,applyDamage:(s,t,n)=>{const b=t.hp;t.hp=Math.max(0,b-n);return b-t.hp;}};return {hero,ally,enemy,ctx};}
const attack={skillId:'basic_attack',targetType:'enemy',tags:['physical'],effects:[{effectType:'damage'}]};
const orbs=c=>c.state.FlowOrbs||[];
test('nonlethal attacks and incoming damage never release FLOW; death releases exactly once',()=>{const {hero,enemy,ctx}=battle('Stoic');resolveSkill(ctx,hero,attack,[3]);resolveSkill(ctx,enemy,attack,[1]);assert.equal(orbs(ctx).length,0);enemy.hp=1;resolveSkill(ctx,hero,attack,[3]);assert.equal(orbs(ctx).length,1);assert.equal(orbs(ctx)[0].sourceUID,3);assert.equal(orbs(ctx)[0].reason,'enemy-death');assert.equal(dropEnemyFlowOrbs(ctx,enemy),0);});
test('all ten former role modes cannot create attack/healing/status/dodge/mitigation orbs',()=>{for(const mode of ['Stoic','Warrior','Slayer','Healer','Tactician','Comrade','Dancer','Rook','Daredevil','Loner']){const {hero,ally,enemy,ctx}=battle(mode);hero.hp=20;hero.statuses=[{statusEffect:'damageCut',magnitude:.5,sourceUID:1}];hero.evasion=1;resolveSkill(ctx,hero,attack,[3]);resolveSkill(ctx,enemy,attack,[1]);resolveSkill(ctx,hero,{targetType:'self',effects:[{effectType:'heal',amount:5}]},[1]);resolveSkill(ctx,hero,{targetType:'enemy',effects:[{effectType:'status',statusEffect:'blind',duration:2}]},[3]);turnStart(ctx,hero,1);assert.equal(orbs(ctx).length,0,mode);assert.equal(hero.flow,0);assert.equal(ally.flow,0);}});
test('multi-hit gives one death reward; multi-kill rewards each defeated enemy',()=>{const {hero,enemy,ctx}=battle('Slayer');enemy.hp=1;const e=actor(4,'enemy');e.hp=1;ctx.actors.push(e);resolveSkill(ctx,hero,{...attack,targetType:'allEnemies',effects:[{effectType:'damage',hits:8}]},[3,4]);assert.equal(orbs(ctx).length,2);});
test('death orb assignment is independent and excludes KO heroes',()=>{const {hero,ally,enemy,ctx}=battle();const ko=actor(4);ko.hp=0;ctx.actors.push(ko);enemy.hp=0;enemy.limitOrbDropCount=4;let i=0;ctx.flowRandom=()=>[0,.99,0,.99][i++];dropEnemyFlowOrbs(ctx,enemy);assert.deepEqual(orbs(ctx).map(o=>o.recipientUID),[1,2,1,2]);advanceFlowOrbs(ctx.state,ctx.actors,2);assert.equal(hero.flow,20);assert.equal(ally.flow,20);assert.equal(ko.flow,0);});
test('spill and all bounces finish before collection; overflow clamps and resources remain independent',()=>{const {hero,enemy,ctx}=battle();enemy.hp=0;hero.flow=95;hero.remainingActionSlots=2;ctx.state.TurnSerial=7;dropEnemyFlowOrbs(ctx,enemy);advanceFlowOrbs(ctx.state,ctx.actors,T.releaseSeconds);assert.equal(hero.flow,95);advanceFlowOrbs(ctx.state,ctx.actors,T.releaseSeconds+T.flightSeconds+.001);assert.equal(hero.flow,100);assert.equal(hero.sp,80);assert.equal(hero.remainingActionSlots,2);assert.equal(ctx.state.TurnSerial,7);});
test('periodic enemy death awards orbs, routine tick does not',()=>{const {hero,enemy,ctx}=battle();enemy.statuses=[{statusEffect:'dot',snapshotPotency:10,sourceUID:1,duration:2}];turnStart(ctx,enemy,1);assert.equal(orbs(ctx).length,0);enemy.hp=1;turnStart(ctx,enemy,2);assert.equal(orbs(ctx).length,1);assert.equal(hero.flow,0);});
test('special death reward excludes its caster; KO recipients and new sessions cancel flights',()=>{const {hero,ally,enemy,ctx}=battle();enemy.hp=1;resolveSkill(ctx,hero,{...attack,isFlowSpecial:true},[3]);assert.equal(orbs(ctx)[0].recipientUID,2);ally.hp=0;advanceFlowOrbs(ctx.state,ctx.actors,2);assert.equal(ally.flow,0);assert.equal(hero.flow,0);});
test('FLOW presentation reuses the original blue death-orb tween',async()=>{const fs=require('node:fs');const source=fs.readFileSync('web-runner/systems/astralFlowKoOrbPresentation.js','utf8');const {getAstralFlowKoOrbFrame:frame}=await import('data:text/javascript,'+encodeURIComponent(source));const orb={source:{x:100,y:20},ground:{x:100,y:60},target:{x:10,y:10},radius:5,spillX:20};assert.equal(frame(orb,.1,0).phase,'spill');assert.equal(frame(orb,.33,0).phase,'bounce-1');assert.ok(frame(orb,.33,0).y<60);assert.equal(frame(orb,.5,0).phase,'bounce-2');assert.equal(frame(orb,.65,0).phase,'bounce-3');assert.equal(frame(orb,.9,0).phase,'fly');assert.equal(frame(orb,1.2,0).phase,'dissolve');assert.ok(fs.readFileSync('web-runner/systems/renderFlowOrbs.mjs','utf8').includes('getAstralFlowKoOrbFrame('));});
