const test=require('node:test'),assert=require('node:assert/strict');
const {resolveSkill}=require('../web-runner/src/core/combatRules.mjs');
const {advanceFlowOrbs,dropEnemyFlowOrbs,spawnDirectedFlowOrb}=require('../web-runner/src/core/flowOrbs.mjs');
const {FLOW_ORB_TUNING:T}=require('../web-runner/src/core/heroDefinitions.mjs');
const actor=(uid,kind='hero')=>({uid,kind,hp:100,maxHP:100,flow:0,statuses:[],stats:{SPD:10,MAG:10}});
function battle(){const hero=actor(1),ally=actor(2),enemy=actor(3,'enemy');const ctx={actors:[hero,ally,enemy],state:{time:0,CombatSessionId:1},random:()=>.2,calculateDamage:()=>10,applyDamage:(s,t,n)=>{const b=t.hp;t.hp=Math.max(0,b-n);return b-t.hp;}};return {hero,ally,enemy,ctx};}
const attack={skillId:'basic_attack',targetType:'enemy',tags:['physical'],effects:[{effectType:'damage'}]};
const orbs=c=>c.state.FlowOrbs||[];

test('enemy deaths do not assign random AF',()=>{const {hero,enemy,ctx}=battle();enemy.hp=1;resolveSkill(ctx,hero,attack,[3]);assert.equal(orbs(ctx).length,0);assert.equal(dropEnemyFlowOrbs(ctx,enemy),0);});
test('a role award uses one explicit blue-orb recipient and charges only on arrival',()=>{const {hero,enemy,ctx}=battle();hero.flow=95;hero.remainingActionSlots=2;ctx.state.TurnSerial=7;assert.equal(spawnDirectedFlowOrb(ctx,enemy,hero,10,'role-action'),1);assert.deepEqual(orbs(ctx).map(orb=>({recipientUID:orb.recipientUID,sourceUID:orb.sourceUID,reason:orb.reason})),[{recipientUID:1,sourceUID:3,reason:'role-action'}]);advanceFlowOrbs(ctx.state,ctx.actors,T.releaseSeconds);assert.equal(hero.flow,95);advanceFlowOrbs(ctx.state,ctx.actors,T.releaseSeconds+T.flightSeconds+.001);assert.equal(hero.flow,100);assert.equal(hero.remainingActionSlots,2);assert.equal(ctx.state.TurnSerial,7);});
test('a role orb rejects dead recipients and cancels when its recipient is defeated or the session changes',()=>{const {hero,ally,enemy,ctx}=battle();hero.hp=0;assert.equal(spawnDirectedFlowOrb(ctx,enemy,hero,10),0);assert.equal(spawnDirectedFlowOrb(ctx,enemy,ally,10),1);ally.hp=0;advanceFlowOrbs(ctx.state,ctx.actors,2);assert.equal(ally.flow,0);ally.hp=100;assert.equal(spawnDirectedFlowOrb(ctx,enemy,ally,10),1);ctx.state.CombatSessionId=2;advanceFlowOrbs(ctx.state,ctx.actors,2);assert.equal(ally.flow,0);});
test('AF orb uses the shared blue token for flight, burst and fallback gem',async()=>{const fs=require('node:fs');const source=fs.readFileSync('web-runner/systems/astralFlowKoOrbPresentation.js','utf8');const renderer=fs.readFileSync('web-runner/systems/renderFlowOrbs.mjs','utf8');const {getAstralFlowKoOrbFrame:frame}=await import('data:text/javascript,'+encodeURIComponent(source));const orb={source:{x:100,y:20},ground:{x:100,y:60},target:{x:10,y:10},radius:5,spillX:20};assert.equal(frame(orb,.1,0).phase,'spill');assert.equal(frame(orb,.33,0).phase,'bounce-1');assert.ok(frame(orb,.33,0).y<60);assert.equal(frame(orb,.5,0).phase,'bounce-2');assert.equal(frame(orb,.65,0).phase,'bounce-3');assert.equal(frame(orb,.9,0).phase,'fly');assert.equal(frame(orb,1.2,0).phase,'dissolve');assert.match(renderer,/ASTRAL_FLOW_METER_BLUE/);assert.match(renderer,/#4dc7ff/);assert.match(renderer,/#bcefff/);assert.match(renderer,/#e9fbff/);assert.doesNotMatch(renderer,/#(?:ff637e|ffd5df|ef4168|fff2f5)/);});
