const test=require('node:test'),assert=require('node:assert/strict');
const {resolveSkill}=require('../web-runner/src/core/combatRules.mjs');
const {advanceFlowOrbs,dropEnemyFlowOrbs}=require('../web-runner/src/core/flowOrbs.mjs');
const {FLOW_ORB_TUNING:T}=require('../web-runner/src/core/heroDefinitions.mjs');
const actor=(uid,kind='hero')=>({uid,kind,hp:100,maxHP:100,flow:0,statuses:[],stats:{SPD:10,MAG:10}});
function battle(){const hero=actor(1),ally=actor(2),enemy=actor(3,'enemy');const ctx={actors:[hero,ally,enemy],state:{time:0,CombatSessionId:1},random:()=>.2,calculateDamage:()=>10,applyDamage:(s,t,n)=>{const b=t.hp;t.hp=Math.max(0,b-n);return b-t.hp;}};return {hero,ally,enemy,ctx};}
const attack={skillId:'basic_attack',targetType:'enemy',tags:['physical'],effects:[{effectType:'damage'}]};
const orbs=c=>c.state.FlowOrbs||[];

test('a killed enemy queues one blue AF orb and charges its assigned hero only on arrival',()=>{const {hero,enemy,ctx}=battle();enemy.hp=1;resolveSkill(ctx,hero,attack,[3]);assert.equal(hero.flow,0);assert.equal(dropEnemyFlowOrbs(ctx,enemy),1);assert.deepEqual(orbs(ctx).map(orb=>({recipientUID:orb.recipientUID,sourceUID:orb.sourceUID,sourceKind:orb.sourceKind,reason:orb.reason})),[{recipientUID:1,sourceUID:3,sourceKind:'enemy',reason:'enemy-death'}]);advanceFlowOrbs(ctx.state,ctx.actors,T.releaseSeconds);assert.equal(hero.flow,0);advanceFlowOrbs(ctx.state,ctx.actors,T.releaseSeconds+T.flightSeconds+.001);assert.equal(hero.flow,10);assert.equal(ctx.state.FlowOrbAudit.arrivedEnemyDeathCount,1);});
test('enemy death orbs have deterministic recipients, no duplicate drop, and never charge dead heroes',()=>{const {hero,ally,enemy,ctx}=battle();const second={...enemy,uid:4};ctx.actors.push(second);assert.equal(dropEnemyFlowOrbs(ctx,enemy),1);assert.equal(dropEnemyFlowOrbs(ctx,enemy),0);assert.equal(dropEnemyFlowOrbs(ctx,second),1);assert.deepEqual(orbs(ctx).map(orb=>orb.recipientUID),[1,1]);hero.hp=0;advanceFlowOrbs(ctx.state,ctx.actors,2);assert.equal(hero.flow,0);assert.equal(ally.flow,0);});
test('100-AF signals dedupe at cap and rearm after flow falls below cap',()=>{const {hero,enemy,ctx}=battle();hero.flow=95;assert.equal(dropEnemyFlowOrbs(ctx,enemy),1);advanceFlowOrbs(ctx.state,ctx.actors,2);assert.deepEqual(ctx.state.PendingFlowThresholds,[{heroUID:1,triggerOrder:1,token:'flow-1-1'}]);const second={uid:4,kind:'enemy',hp:100,x:0,y:0};ctx.actors.push(second);assert.equal(dropEnemyFlowOrbs(ctx,second),1);advanceFlowOrbs(ctx.state,ctx.actors,3);assert.equal(ctx.state.PendingFlowThresholds.length,1);hero.flow=90;const third={uid:5,kind:'enemy',hp:100,x:0,y:0};ctx.actors.push(third);assert.equal(dropEnemyFlowOrbs(ctx,third),1);advanceFlowOrbs(ctx.state,ctx.actors,4);assert.deepEqual(ctx.state.PendingFlowThresholds.map(signal=>signal.triggerOrder),[1,2]);});
test('AF orb uses the shared blue token for flight, burst and fallback gem',async()=>{const fs=require('node:fs');const source=fs.readFileSync('web-runner/systems/astralFlowKoOrbPresentation.js','utf8');const renderer=fs.readFileSync('web-runner/systems/renderFlowOrbs.mjs','utf8');const {getAstralFlowKoOrbFrame:frame}=await import('data:text/javascript,'+encodeURIComponent(source));const orb={source:{x:100,y:20},ground:{x:100,y:60},target:{x:10,y:10},radius:5,spillX:20};assert.equal(frame(orb,.1,0).phase,'spill');assert.equal(frame(orb,.33,0).phase,'bounce-1');assert.ok(frame(orb,.33,0).y<60);assert.equal(frame(orb,.5,0).phase,'bounce-2');assert.equal(frame(orb,.65,0).phase,'bounce-3');assert.equal(frame(orb,.9,0).phase,'fly');assert.equal(frame(orb,1.2,0).phase,'fly');assert.equal(frame(orb,1.45,0).phase,'dissolve');assert.match(renderer,/ASTRAL_FLOW_METER_BLUE/);assert.match(renderer,/#4dc7ff/);assert.match(renderer,/#bcefff/);assert.match(renderer,/#e9fbff/);assert.doesNotMatch(renderer,/#(?:ff637e|ffd5df|ef4168|fff2f5)/);});

test('three simultaneous enemy-death gems remain visible through the 650ms flight and award AF once on impact',async()=>{
 const {getAstralFlowKoOrbFrame:frame}=await import('data:text/javascript,'+encodeURIComponent(require('node:fs').readFileSync('web-runner/systems/astralFlowKoOrbPresentation.js','utf8')));
 const {hero,ally,enemy,ctx}=battle();ctx.state.time=5;const thirdHero={...ally,uid:5};const enemies=[enemy,{...enemy,uid:4,x:20},{...enemy,uid:6,x:40}];ctx.actors=[hero,ally,thirdHero,...enemies];
 for(const defeated of enemies){defeated.hp=0;assert.equal(dropEnemyFlowOrbs(ctx,defeated),1);}
 const born=5,early=born+T.releaseSeconds+.05,mid=born+T.releaseSeconds+T.flightSeconds/2,preImpact=born+T.releaseSeconds+T.flightSeconds-.001,impact=born+T.releaseSeconds+T.flightSeconds;
 assert.equal(T.flightSeconds,.65);assert.equal(orbs(ctx).length,3);assert.equal(hero.flow,0);
 advanceFlowOrbs(ctx.state,ctx.actors,born);assert.equal(orbs(ctx).length,3);assert.equal(hero.flow,0);
 const visual={source:{x:100,y:20},ground:{x:100,y:60},target:{x:10,y:10},radius:5,spillX:20};
 for(const now of [early,mid,preImpact]){advanceFlowOrbs(ctx.state,ctx.actors,now);assert.equal(orbs(ctx).length,3);assert.equal(hero.flow,0);assert.equal(frame(visual,now,born).phase,'fly');}
 advanceFlowOrbs(ctx.state,ctx.actors,impact);assert.equal(orbs(ctx).length,3);assert.equal(hero.flow,30);assert.equal(ctx.state.FlowOrbAudit.arrivedEnemyDeathCount,3);
 advanceFlowOrbs(ctx.state,ctx.actors,impact+.05);assert.equal(orbs(ctx).length,3);assert.equal(hero.flow,30);assert.equal(ctx.state.FlowOrbAudit.arrivedEnemyDeathCount,3);
 advanceFlowOrbs(ctx.state,ctx.actors,impact+T.collectFlashSeconds+.001);assert.equal(orbs(ctx).length,0);assert.equal(hero.flow,30);
});
