const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');

function sliceBetween(src, startMarker, endMarker) {
  const start = src.indexOf(startMarker);
  assert.notEqual(start, -1, `missing ${startMarker}`);
  const end = src.indexOf(endMarker, start);
  assert.notEqual(end, -1, `missing ${endMarker}`);
  return src.slice(start, end);
}

test('heal bloom module uses a staggered upward GSAP fountain instead of a radial burst', () => {
  const src = fs.readFileSync(path.join(__dirname, '..', 'web-runner', 'src', 'core', 'healBloomAnimation.mjs'), 'utf8');
  assert.match(src, /import\s+\{\s*gsap\s*\}\s+from\s+'\.\/gsapShim\.mjs';/);
  assert.match(src, /glyph: '➕',/);
  assert.match(src, /fontWeight: 800,/);
  assert.match(src, /color: '#A0FE0B',/);
  assert.match(src, /const total = Math\.max\(8, Math\.min\(14, Math\.floor\(Number\(count \|\| 12\)\)\)\);/);
  assert.match(src, /const HEAL_BLOOM_WIDTH_SCALE = 0\.8;/);
  assert.match(src, /targetUID: Number\(targetUID \|\| 0\),/);
  assert.match(src, /ownerUID: Number\(ownerUID \|\| targetUID \|\| 0\),/);
  assert.match(src, /presentation: presentation === 'major' \? 'major' : 'minor',/);
  assert.match(src, /const tl = gsap\.timeline\(\);/);
  assert.match(src, /const dx = random\(-24, 24\) \* HEAL_BLOOM_WIDTH_SCALE;/);
  assert.match(src, /const dy = -random\(44, 78\);/);
  assert.match(src, /const delay = \(i \/ total\) \* 0\.22;/);
  assert.match(src, /const riseDuration = 1\.05 - delay;/);
  assert.doesNotMatch(src, /tl\.delay\(delay\)/);
  assert.match(src, /ease: 'sine\.out',\n\s*\}, delay\);/);
  assert.match(src, /duration: riseDuration,/);
  assert.match(src, /ease: 'sine\.out'/);
  assert.match(src, /ease: 'sine\.inOut'/);
  assert.doesNotMatch(src, /back\.out|power2\.out/);
  assert.match(src, /const rotation = random\(-12, 12\);/);
});

test('heal bloom marks its owner and clears after the final particle completes', async () => {
  const { createHealBloom } = await import('../web-runner/src/core/healBloomAnimation.mjs');
  const animation = createHealBloom({ x: 88, y: 144, targetUID: 17, ownerUID: 3, count: 8, presentation: 'major' });
  assert.equal(animation.targetUID, 17);
  assert.equal(animation.ownerUID, 3);
  assert.equal(animation.complete, false);
  await new Promise(resolve => setTimeout(resolve, 1600));
  assert.equal(animation.complete, true);
});

test('app heal path plays a ten-frame green swirl with Faze-style front motes', () => {
  const appSrc = fs.readFileSync(path.join(__dirname, '..', 'web-runner', 'app.js'), 'utf8');
  const spawnSrc = sliceBetween(appSrc, 'function spawnPendingDamageNumbers', 'const RUNTIME_FINGERPRINT');
  const renderSrc = fs.readFileSync(path.join(__dirname, '..', 'web-runner', 'systems', 'renderRuntime.js'), 'utf8');
  assert.match(appSrc, /import\s+\{\s*createHealBloom\s*\}\s+from\s+'\.\/src\/core\/healBloomAnimation\.mjs';/);
  assert.match(fs.readFileSync(path.join(__dirname, '..', 'web-runner', 'modules', 'heroCommands.mjs'), 'utf8'), /HeroRestFeetPosByUID/);
  assert.ok(spawnSrc.includes("['hero', 'enemy'].includes(d.targetKind)"));
  assert.doesNotMatch(spawnSrc, /d\.targetKind === 'bar'/);
  assert.match(spawnSrc, /d\.healBloomAnimation = createHealBloom\(\{/);
  assert.match(spawnSrc, /targetUID: d\.targetUID,/);
  assert.match(spawnSrc, /ownerUID: d\.ownerUID,/);
  assert.match(spawnSrc, /presentation: d\.healPresentation,/);
  assert.match(spawnSrc, /gameState\.healBlooms = Array\.isArray\(gameState\.healBlooms\) \? gameState\.healBlooms : \[\];/);
  assert.match(spawnSrc, /gameState\.healBlooms\.push\(d\.healBloomAnimation\);/);
  assert.match(renderSrc, /const renderHealBlooms = \(layer = 'back'\) => \{/);
  assert.match(renderSrc, /bloom\.presentation === 'major' && images\.CombatHealSwirl/);
  assert.match(renderSrc, /const frameCount = 10;/);
  assert.match(renderSrc, /Math\.floor\(stage\.progress \* frameCount\)/);
  assert.match(renderSrc, /if \(layer === 'back'\) \{[\s\S]*ctx\.drawImage\(images\.CombatHealSwirl/);
  assert.match(renderSrc, /const splitY = frameHeight \* 0\.7;/);
  assert.match(renderSrc, /drawY \+ drawSize \* 0\.7, drawWidth, drawSize \* 0\.3/);
  assert.match(renderSrc, /HeroRestFeetPosByUID\?\.\[targetUID\]/);
  assert.match(renderSrc, /const enemyFeet = targetActor\?\.kind === 'enemy'/);
  assert.match(renderSrc, /targetActor\.originY \?\? targetActor\.y \?\? 0\) \+ Math\.max\(24, Number\(state\.globals\.EnemySize \|\| 40\)\) \/ 2/);
  assert.match(renderSrc, /const targetFeet = restFeet \|\| enemyFeet;/);
  assert.match(renderSrc, /HeroRenderHeightByUID\?\.\[targetUID\]/);
  assert.match(renderSrc, /HeroRenderWidthByUID\?\.\[targetUID\]/);
  assert.match(renderSrc, /const drawY = anchor\.y - drawSize \* 0\.78;/);
  assert.match(renderSrc, /const drawWidth = Math\.max\(heroHeight \* 1\.9, heroWidth \* 1\.55\);/);
  assert.match(renderSrc, /images\.CombatHealBurst && stage\.progress < 0\.42/);
  assert.match(renderSrc, /const burstFrames = 4;/);
  assert.match(renderSrc, /anchor\.y - heroHeight \* 0\.43/);
  assert.match(renderSrc, /const burstWidth = Math\.max\(heroHeight \* 1\.25, heroWidth \* 1\.15\);/);
  assert.match(renderSrc, /\.filter\(particle => particle && Number\(particle\.opacity \|\| 0\) > 0\.02\)\.slice\(0, 7\)/);
  assert.match(renderSrc, /if \(layer === 'front'\) \{/);
  assert.match(renderSrc, /ctx\.fillStyle = '#B9FFD0';/);
  assert.match(renderSrc, /Number\(particle\.x \|\| 0\) \* 0\.8 \* layoutScale/);
  assert.match(renderSrc, /`if \(images\.CombatHealMotes && stage\.progress > 0\.34\) \{\n\s*const moteT[\s\S]*const width = Math\.max\(34, 46 \* layoutScale\);/);
  assert.match(renderSrc, /"const width = Math\.max\(54, 72 \* layoutScale\);",[\s\S]*"const width = Math\.max\(38, 48 \* layoutScale\);"/);
  assert.match(renderSrc, /const bloomStage = \(bloom\) => \{/);
  assert.doesNotMatch(renderSrc, /images\.CombatHealBloom/);
  assert.doesNotMatch(renderSrc, /ctx\.fillRect\(-arm \/ 2, -length \/ 2, arm, length\);/);
  assert.match(renderSrc, /renderHealBlooms\('back'\);[\s\S]*\/\/ Render hero portraits/);
  assert.match(renderSrc, /renderHealBlooms\('front'\);[\s\S]*\/\/ Render hero damage\/heal text/);
  assert.match(renderSrc, /HeroRestFeetPosByUID/);
  const hooksSrc = fs.readFileSync(path.join(__dirname, '..', 'web-runner', 'systems', 'devBrowserTestHooks.js'), 'utf8');
  assert.match(hooksSrc, /setupHealBloomScenario/);
  assert.match(hooksSrc, /replayHealBloomScenario/);
  assert.match(hooksSrc, /captureHealBloomFrames/);
  assert.match(hooksSrc, /canvas\.toDataURL\('image\/webp', 0\.8\)/);
  assert.match(hooksSrc, /window\.requestAnimationFrame\(onFrame\)/);
  assert.match(hooksSrc, /sawActive && activeCount === 0/);
  assert.match(hooksSrc, /Live QA heal replay: every browser frame/);
  assert.match(hooksSrc, /scenario === 'heal-bloom'/);
});

test('party regen uses a persistent hero shimmer instead of a tint overlay', () => {
  const src = fs.readFileSync(path.join(__dirname, '..', 'web-runner', 'systems', 'renderRuntime.js'), 'utf8');
  const shimmerSrc = sliceBetween(src, 'const renderHeroRegenShimmer', 'const renderEnemyTaintedGround');
  assert.match(src, /const hasPersistentHeroRegenOverlay = \(\) => \{/);
  assert.match(src, /const regens = Array\.isArray\(state\.globals\.PartyRegens\) \? state\.globals\.PartyRegens : \[\];/);
  assert.match(shimmerSrc, /const renderHeroRegenShimmer = \(drawX, drawY, scaledW, scaledH, seed = 0\) => \{/);
  assert.match(shimmerSrc, /const lineCount = 4;/);
  assert.match(shimmerSrc, /const diamondCount = 3;/);
  assert.doesNotMatch(shimmerSrc, /ctx\.clip\(\);/);
  assert.match(shimmerSrc, /const lineX = drawX \+ scaledW \* \(0\.16 \+ i \* 0\.2\);/);
  assert.match(shimmerSrc, /ctx\.globalAlpha = 0\.096 \+ normalized \* 0\.216;/);
  assert.match(shimmerSrc, /ctx\.fillStyle = '#A0FE0B';/);
  assert.match(shimmerSrc, /const cycle = \(shimmerNow \* 0\.22 \+ seed \* 0\.09 \+ i \* 0\.31\) % 1;/);
  assert.match(shimmerSrc, /const diamondSize = Math\.max\(3, scaledW \* 0\.045\);/);
  assert.match(shimmerSrc, /const alpha = cycle < 0\.12 \? \(cycle \/ 0\.12\) \* 1\.12 : \(1 - cycle\) \* 1\.12;/);
  assert.match(shimmerSrc, /ctx\.globalAlpha = Math\.max\(0, Math\.min\(1, alpha\)\);/);
  assert.match(shimmerSrc, /ctx\.fillStyle = '#FFFFFF';/);
  assert.match(shimmerSrc, /ctx\.shadowColor = '#F4E96A';/);
  assert.match(shimmerSrc, /ctx\.quadraticCurveTo\(diamondSize \* 0\.55, -diamondSize \* 0\.35, diamondSize, 0\);/);
  assert.match(src, /hasPersistentHeroRegenOverlay\(\)[\s\S]*renderHeroRegenShimmer\(drawX, drawY, scaledW, scaledH, hero\.uid\);/);
  assert.match(src, /if \(hero && isHitFlashActive\(hero\.uid\)\) \{/);
  assert.doesNotMatch(src, /tone === 'regen'/);
});
