const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

test('app wires super gem hooks for settle, spend, and decomposition', () => {
  const src = fs.readFileSync('web-runner/app.js', 'utf8');
  const runtimeSrc = fs.readFileSync('web-runner/systems/superGemRuntime.js', 'utf8');
  const renderRuntimeSrc = fs.readFileSync('web-runner/systems/renderRuntime.js', 'utf8');
  const boardStateSrc = fs.readFileSync('web-runner/src/core/superGemBoardState.mjs', 'utf8');
  const renderBoardSrc = fs.readFileSync('web-runner/systems/renderBoard.js', 'utf8');
  assert.match(src, /import\s+\{[\s\S]*getSuperGemAtCanvasPoint[\s\S]*getSuperGemAtCell[\s\S]*spendSuperGem[\s\S]*syncSuperGemShapes[\s\S]*\}\s+from\s+'\.\/src\/core\/superGemBoardState\.mjs';/);
  assert.match(src, /import \* as superGemRuntime from '\.\/systems\/superGemRuntime\.js';/);
  assert.match(src, /superGems:\s*\[\],/);
  assert.match(src, /superGemCellMap:\s*new Map\(\),/);
  assert.doesNotMatch(src, /function settleSuperGemShapes\(reason = 'unknown'\)/);
  assert.doesNotMatch(src, /function resolveSuperGemDecomposition\(reason = 'unknown'\)/);
  assert.doesNotMatch(src, /function spendSuperGem\(superGem, reason = 'tap'\)/);
  assert.match(src, /const tappedSuperGem = getSuperGemAtCanvasPoint\(\{\s*gameState,\s*mx,\s*my,/s);
  assert.match(src, /const tappedSuperGem = getSuperGemAtCell\(gameState, gem\.cellR, gem\.cellC\);/);
  assert.match(src, /if \(tappedSuperGem\) \{\s*spendSuperGem\(\{/s);
  assert.match(src, /resolveSuperGemDecomposition\(\{ gameState, state, reason: 'pre-refill' }\);/);
  assert.match(src, /settleSuperGemShapes\(\{ gameState, state, boardGeometry, reason: 'immediate-fill' }\);/);
  assert.match(src, /settleSuperGemShapes\(\{ gameState, state, boardGeometry, reason: 'refill-gem-board' }\);/);
  assert.match(src, /syncSuperGemShapes\(\{ gameState, state, boardGeometry, reason: 'draw-frame' }\);/);
  assert.match(boardStateSrc, /export function getSuperGemAtCanvasPoint\(/);
  assert.match(boardStateSrc, /export function settleSuperGemShapes\(/);
  assert.match(boardStateSrc, /export function resolveSuperGemDecomposition\(/);
  assert.match(boardStateSrc, /export function spendSuperGem\(/);
  assert.match(boardStateSrc, /const afterEnergy = Math\.max\(0, beforeEnergy - Number\(superGemCost \|\| 0\)\);/);
  assert.match(renderBoardSrc, /import \{ getSuperGemRenderImage, getSuperGemRenderRect \} from '\.\.\/src\/core\/superGemRender\.mjs';/);
  assert.match(renderRuntimeSrc, /renderBoard\.renderBoard\(ctx, gameState, uiState\.getUIState\(\), animationMath, \{\\n      boardGeometry,\\n      worldToCanvas,\\n      layoutScale,\\n      gemFrameImages,\\n      superGemFrameImages,\\n      superGemRainbowImage,\\n      now,/);
  assert.match(runtimeSrc, /const SUPER_GEM_COST = 4;/);
  assert.match(runtimeSrc, /randomIntInclusive\(2, 4, rng\)/);
  assert.match(runtimeSrc, /randomIntInclusive\(4, 6, rng\)/);
  assert.match(runtimeSrc, /randomIntInclusive\(8, 16, rng\)/);
  assert.match(runtimeSrc, /superGemClusterVisualOnly/);
  assert.match(runtimeSrc, /superGemClusterApplyTotalOnHit/);
  assert.match(runtimeSrc, /export function armPendingSuperGemAttack\(/);
  assert.match(runtimeSrc, /export function executePendingSuperGemAction\(/);
  assert.match(runtimeSrc, /PendingSuperGemAction/);
  assert.match(renderRuntimeSrc, /SpawnDamageText', finalDmg, targetX, targetY, 'damage', targetKind/);
  assert.match(renderRuntimeSrc, /ApplyDamageToTarget', hit\.targetUID, clusterApplyTotal/);
  assert.match(runtimeSrc, /ArmPowerAmpFixed', actorUID, 5/);
  assert.match(src, /const resolvedPendingSuperGem = superGemRuntime\.executePendingSuperGemAction\(\{/);
});
