export function createInitialGameState() {
  return {
    selectedHero: 0,
    selectedEnemy: 0,
    playerTurn: true,
    partyHP: [42, 35, 30, 40],
    partyMaxHP: [42, 35, 30, 40],
    enemyHP: [50, 60, 55],
    enemyMaxHP: [50, 60, 55],
    // Overlay state - NavMenu opens overlay window
    // Gem board state
    gems: [], // array of gem objects {cellC, cellR, color, x, y}
    selectedGems: [], // indices of selected gems
    boardCreated: false,
    gridBounds: null, // bounds of grid_placeholder area for centering
    grid: [], // 2D grid of gem uid or 0
    nextGemUID: 1,
    bootstrapRng: {
      enabled: false,
      next: null,
      gemInitRemaining: 0,
    },
    selectionLocked: false,
    enemyTurnKicked: false,
    buffRollTimer: 0,
    buffIconPresentation: null,
    gemMergeFx: null,
    yellowCasino: {
      active: false,
      phase: 'idle',
      queue: [],
      index: 0,
      current: null,
      telegraphUntil: 0,
    },
    refillBounce: {
      active: false,
      queue: [],
      index: 0,
      current: null,
    },
    superGems: [],
    superGemCellMap: new Map(),
    superGemSignature: '',
    nextSuperGemId: 1,
    storyCardLine: {
      text: '',
      animUntil: 0,
    },
    storyCardLayout: {
      x: 0,
      y: 0,
      w: 0,
      h: 0,
      initialized: false,
      trigger: '',
    },
    tomesLayout: {
      entryPoint: 'map-locale',
      selectedIndex: 0,
      hitZones: null,
      gallery: [
        {
          id: 'tome-cinder-codex',
          name: 'Cinder Codex',
          discovered: true,
          rarity: 'Rare',
          buffSlot: { stat: 'ATK', mode: 'flat', value: 1, cadenceTurns: 4 },
          enemyDebuffSlot: null,
        },
        {
          id: 'tome-gale-archive',
          name: 'Gale Archive',
          discovered: true,
          rarity: 'Epic',
          buffSlot: { stat: 'SPD', mode: 'flat', value: 1, cadenceTurns: 5 },
          enemyDebuffSlot: { stat: 'CRIT', mode: 'pct', value: 0.08, cadenceTurns: 0 },
        },
        {
          id: 'tome-ward-index',
          name: 'Ward Index',
          discovered: false,
          rarity: 'Legendary',
          buffSlot: { stat: 'DEF', mode: 'flat', value: 1, cadenceTurns: 6 },
          enemyDebuffSlot: null,
        },
        {
          id: 'tome-hollow-scripture',
          name: 'Hollow Scripture',
          discovered: false,
          rarity: 'Epic',
          buffSlot: { stat: 'RES', mode: 'flat', value: 1, cadenceTurns: 5 },
          enemyDebuffSlot: { stat: 'ATK', mode: 'pct', value: 0.06, cadenceTurns: 0 },
        },
      ],
    },
    artifactsLayout: {
      entryPoint: 'map-locale',
      selectedIndex: 0,
      hitZones: null,
      gallery: [
        {
          id: 'artifact-fang-mark',
          name: 'Fang Mark',
          discovered: true,
          rarity: 'Rare',
          passiveHook: { key: 'regen_tick', mode: 'flat', value: 2, cadenceTurns: 5 },
          visibleCombatFx: false,
        },
        {
          id: 'artifact-iron-crest',
          name: 'Iron Crest',
          discovered: true,
          rarity: 'Epic',
          passiveHook: { key: 'defense_boost', mode: 'flat', value: 1, cadenceTurns: 15 },
          visibleCombatFx: false,
        },
        {
          id: 'artifact-night-coin',
          name: 'Night Coin',
          discovered: false,
          rarity: 'Legendary',
          passiveHook: { key: 'enemy_slow', mode: 'pct', value: 0.06, cadenceTurns: 15 },
          visibleCombatFx: false,
        },
        {
          id: 'artifact-ward-prism',
          name: 'Ward Prism',
          discovered: false,
          rarity: 'Epic',
          passiveHook: { key: 'resist_guard', mode: 'flat', value: 1, cadenceTurns: 8 },
          visibleCombatFx: false,
        },
      ],
    },
    mountsLayout: {
      entryPoint: 'map-locale',
      selectedIndex: 0,
      hitZones: null,
      gallery: [
        {
          id: 'mount-ash-runner',
          name: 'Ash Runner',
          discovered: true,
          rarity: 'Rare',
          siblingFamily: 'progression-gallery',
          vaultCompatibilityTier: 1,
          passiveHook: { key: 'turn_speed', mode: 'flat', value: 1, cadenceTurns: 4 },
        },
        {
          id: 'mount-ridge-boar',
          name: 'Ridge Boar',
          discovered: true,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          vaultCompatibilityTier: 2,
          passiveHook: { key: 'impact_guard', mode: 'flat', value: 1, cadenceTurns: 7 },
        },
        {
          id: 'mount-aether-drake',
          name: 'Aether Drake',
          discovered: false,
          rarity: 'Legendary',
          siblingFamily: 'progression-gallery',
          vaultCompatibilityTier: 3,
          passiveHook: { key: 'opening_strike', mode: 'pct', value: 0.05, cadenceTurns: 0 },
        },
        {
          id: 'mount-fog-stag',
          name: 'Fog Stag',
          discovered: false,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          vaultCompatibilityTier: 2,
          passiveHook: { key: 'resist_guard', mode: 'flat', value: 1, cadenceTurns: 8 },
        },
      ],
    },
    collectiblesLayout: {
      entryPoint: 'map-locale',
      selectedIndex: 0,
      hitZones: null,
      gallery: [
        {
          id: 'collectible-astral-seal',
          name: 'Astral Seal',
          discovered: true,
          rarity: 'Rare',
          siblingFamily: 'progression-gallery',
          setTag: 'seal-archive',
          passiveHook: { key: 'wallet_bonus', mode: 'pct', value: 0.04, cadenceTurns: 0 },
        },
        {
          id: 'collectible-vault-shard',
          name: 'Vault Shard',
          discovered: true,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          setTag: 'ward-breaker',
          passiveHook: { key: 'ward_break_boost', mode: 'flat', value: 1, cadenceTurns: 0 },
        },
        {
          id: 'collectible-orbit-emblem',
          name: 'Orbit Emblem',
          discovered: false,
          rarity: 'Legendary',
          siblingFamily: 'progression-gallery',
          setTag: 'orbit-regalia',
          passiveHook: { key: 'drop_weight', mode: 'pct', value: 0.05, cadenceTurns: 0 },
        },
      ],
    },
    relicsLayout: {
      entryPoint: 'map-locale',
      selectedIndex: 0,
      hitZones: null,
      gallery: [
        {
          id: 'relic-astral-seal',
          name: 'Astral Seal',
          discovered: true,
          rarity: 'Rare',
          siblingFamily: 'progression-gallery',
          setTag: 'seal-archive',
          passiveHook: { key: 'wallet_bonus', mode: 'pct', value: 0.04, cadenceTurns: 0 },
        },
        {
          id: 'relic-vault-shard',
          name: 'Vault Shard',
          discovered: true,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          setTag: 'ward-breaker',
          passiveHook: { key: 'ward_break_boost', mode: 'flat', value: 1, cadenceTurns: 0 },
        },
        {
          id: 'relic-orbit-emblem',
          name: 'Orbit Emblem',
          discovered: false,
          rarity: 'Legendary',
          siblingFamily: 'progression-gallery',
          setTag: 'orbit-regalia',
          passiveHook: { key: 'drop_weight', mode: 'pct', value: 0.05, cadenceTurns: 0 },
        },
        {
          id: 'relic-echo-trophy',
          name: 'Echo Trophy',
          discovered: false,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          setTag: 'echo-line',
          passiveHook: { key: 'chest_meter', mode: 'pct', value: 0.03, cadenceTurns: 0 },
        },
      ],
    },
    petsLayout: {
      entryPoint: 'map-locale',
      selectedIndex: 0,
      hitZones: null,
      gallery: [
        {
          id: 'pet-ember-sprite',
          name: 'Ember Sprite',
          discovered: true,
          rarity: 'Rare',
          siblingFamily: 'progression-gallery',
          milestoneSlots: 5,
          deploymentSlots: 2,
          passiveHook: { key: 'opening_haste', mode: 'flat', value: 1, cadenceTurns: 3 },
        },
        {
          id: 'pet-mossback',
          name: 'Mossback',
          discovered: true,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          milestoneSlots: 5,
          deploymentSlots: 2,
          passiveHook: { key: 'guard_bloom', mode: 'flat', value: 1, cadenceTurns: 5 },
        },
        {
          id: 'pet-velvet-fox',
          name: 'Velvet Fox',
          discovered: false,
          rarity: 'Legendary',
          siblingFamily: 'progression-gallery',
          milestoneSlots: 5,
          deploymentSlots: 2,
          passiveHook: { key: 'crit_trail', mode: 'pct', value: 0.05, cadenceTurns: 0 },
        },
        {
          id: 'pet-lantern-jelly',
          name: 'Lantern Jelly',
          discovered: false,
          rarity: 'Epic',
          siblingFamily: 'progression-gallery',
          milestoneSlots: 5,
          deploymentSlots: 2,
          passiveHook: { key: 'mana_drift', mode: 'flat', value: 1, cadenceTurns: 4 },
        },
      ],
    },
    idleFarmLayout: {
      entryPoint: 'astral-flow-nav',
      hitZones: null,
      config: {
        heroNames: ['Falie', 'Kojonn'],
        loopForever: true,
        enemySlots: 2,
        maxVisibleEnemies: 2,
        secondEnemyChance: 0.45,
        hitsToKill: 3,
        attackIntervalSec: 3,
        enemySpawnDelaySec: 1.5,
        rewardCadenceSec: 18,
        goldPerCadence: 1,
        scrapPerCadence: 1,
      },
      metaBonuses: {
        goldGainPct: 0,
        resourceGainPct: 0,
      },
      rewardLedger: {
        unclaimedEnergy: 0,
        claimedEnergyTotal: 0,
        unclaimedTokens: {
          SAND: 0,
          BONE_CHIP: 0,
          SLIME: 0,
          HORN: 0,
          SHELL: 0,
        },
        claimedTokensTotal: {
          SAND: 0,
          BONE_CHIP: 0,
          SLIME: 0,
          HORN: 0,
          SHELL: 0,
        },
      },
      emissionState: null,
      session: null,
    },
    evolutionLayout: {
      entryPoint: 'map-locale',
      selectedLevel: 0,
      hitZones: null,
      ladder: [
        { level: 1, stat: 'HP', bonusText: '+25 HP', softCurrency: 'Astral Dust', cost: 40, status: 'preview-open' },
        { level: 2, stat: 'ATK', bonusText: '+3 ATK', softCurrency: 'Astral Dust', cost: 55, status: 'preview-open' },
        { level: 3, stat: 'DEF', bonusText: '+3 DEF', softCurrency: 'Astral Dust', cost: 70, status: 'preview-open' },
        { level: 4, stat: 'MAG', bonusText: '+4 MAG', softCurrency: 'Astral Dust', cost: 90, status: 'preview-open' },
        { level: 5, stat: 'RES', bonusText: '+4 RES', softCurrency: 'Astral Dust', cost: 110, status: 'preview-open' },
        { level: 6, stat: 'SPD', bonusText: '+2 SPD', softCurrency: 'Astral Dust', cost: 135, status: 'preview-open' },
        { level: 7, stat: 'Core', bonusText: 'Trait lattice unlock seam', softCurrency: 'Astral Dust', cost: 165, status: 'future-capstone' },
      ],
      researchGates: [
        { id: 'evo-gate-falie-aegis', hero: 'Falie', node: 'Aegis Theory', unlockLevel: 3, state: 'future-research' },
        { id: 'evo-gate-huun-ambush', hero: 'Huun', node: 'Ambush Weave', unlockLevel: 4, state: 'future-research' },
        { id: 'evo-gate-runa-ward', hero: 'Runa', node: 'Ward Bloom', unlockLevel: 5, state: 'future-research' },
        { id: 'evo-gate-kojonn-blight', hero: 'Kojonn', node: 'Blight Script', unlockLevel: 6, state: 'future-research' },
      ],
    },
    homesteadLayout: {
      entryPoint: 'map-locale',
      selectedSlot: 0,
      hitZones: null,
      scene: {
        theme: 'garden-shell',
        slots: [
          { id: 'home-slot-1', kind: 'emitter-pad', unlocked: true, buildState: 'empty' },
          { id: 'home-slot-2', kind: 'workshop-node', unlocked: true, buildState: 'empty' },
          { id: 'home-slot-3', kind: 'storage-node', unlocked: false, buildState: 'locked' },
          { id: 'home-slot-4', kind: 'garden-node', unlocked: false, buildState: 'locked' },
        ],
        placeholderEmissions: [
          { key: 'soft_currency', cadenceSeconds: 300, value: 10 },
          { key: 'material_scrap', cadenceSeconds: 600, value: 1 },
        ],
      },
    },
    chestsLayout: {
      entryPoint: 'menu-nav',
      activeTab: 'Common',
      progress: {
        current: 36,
        target: 100,
        milestoneReward: 'Tier Chest',
      },
      hitZones: null,
      tabs: [
        { id: 'Common', label: 'Common', tier: 1, chestCount: 3 },
        { id: 'Rare', label: 'Rare', tier: 2, chestCount: 2 },
        { id: 'Epic', label: 'Epic', tier: 3, chestCount: 1 },
        { id: 'Legendary', label: 'Legendary', tier: 4, chestCount: 0 },
      ],
      retentionButtons: [
        { id: 'homestead', title: 'Enter Homestead', subtitle: 'Map Locale', targetLayout: 'homesteadLayout', fill: '#f4efcf', stroke: '#a08f41', text: '#5a4d17' },
        { id: 'collectibles', title: 'Enter Collectibles', subtitle: 'Map Locale', targetLayout: 'collectiblesLayout', fill: '#f1e0f7', stroke: '#8e61a4', text: '#4a275d' },
        { id: 'relics', title: 'Enter Relics', subtitle: 'Map Locale', targetLayout: 'relicsLayout', fill: '#f1e0f7', stroke: '#8e61a4', text: '#4a275d' },
        { id: 'pets', title: 'Enter Pets', subtitle: 'Map Locale', targetLayout: 'petsLayout', fill: '#e7f2d5', stroke: '#7e9e54', text: '#324819' },
        { id: 'evolution', title: 'Enter Evolution', subtitle: 'Soft Currency', targetLayout: 'evolutionLayout', fill: '#e3ecfb', stroke: '#5a79b8', text: '#20385f' },
        { id: 'mounts', title: 'Enter Mounts', subtitle: 'Map Locale', targetLayout: 'mountsLayout', fill: '#d9f2da', stroke: '#4a8b4f', text: '#1f4a24' },
        { id: 'artifacts', title: 'Enter Artifacts', subtitle: 'Map Locale', targetLayout: 'artifactsLayout', fill: '#d7e7f8', stroke: '#3c6f9f', text: '#17324a' },
        { id: 'tomes', title: 'Enter Tomes', subtitle: 'Map Locale', targetLayout: 'tomesLayout', fill: '#f3ddaa', stroke: '#8d6d2a', text: '#2f2412' },
      ],
      rewardsByTab: {
        Common: ['Pet Fragment x5', 'Relic Scrap x8', 'Coins x250'],
        Rare: ['Pet Fragment x10', 'Relic Token x2', 'Coins x600'],
        Epic: ['Pet Core x1', 'Relic Token x4', 'Coins x1200'],
        Legendary: ['Pet Core x2', 'Ancient Relic x1', 'Coins x3000'],
      },
    },
    task015Trace: {
      storycardPlacement: [],
      yellowQueue: [],
      yellowRefillQueue: [],
      yellowWrites: [],
      yellowAnimation: [],
    },
    lastTurnPhase: null,
    baseSummary: '',
    startupLoad: {
      active: true,
      phase: 'boot',
      label: 'Booting runtime...',
      progress: 0,
    },
  }
}
