const freezeRecords = (records) => Object.freeze(records.map((record) => Object.freeze(record)));

const line = (id, speakerId, textKey, cameraShotId, extras = {}) => Object.freeze({
  id,
  type: 'line',
  ...(speakerId ? { speakerId } : {}),
  textKey,
  cameraShotId,
  ...extras,
});

export const WISHFIRE_WARP_CROSSING_SCENE_ID = 'wishfire-warp-crossing-arrival';

export const WISHFIRE_WARP_CROSSING_CONTENT = Object.freeze({
  version: 1,
  contentPackId: 'wishfire-warp-crossing-preview',
  defaultLocale: 'en',
  characters: freezeRecords([
    {
      id: 'hondo',
      displayNameKey: 'character.hondo.name',
      portrait: Object.freeze({
        kind: 'illustration',
        assetRef: 'assets/narrative/characters/hondo.png',
      }),
    },
    {
      id: 'fara',
      displayNameKey: 'character.fara.name',
      portrait: Object.freeze({
        kind: 'illustration',
        assetRef: 'assets/narrative/characters/fara.png',
      }),
    },
    {
      id: 'kaja',
      displayNameKey: 'character.kaja.name',
      portrait: Object.freeze({
        kind: 'illustration',
        assetRef: 'assets/narrative/characters/kaja.png',
      }),
    },
    {
      id: 'runa',
      displayNameKey: 'character.runa.name',
      portrait: Object.freeze({
        kind: 'illustration',
        assetRef: 'assets/narrative/characters/runa.png',
      }),
    },
  ]),
  backgrounds: freezeRecords([
    {
      id: 'wishfire-goldrin-wilds-warpfall',
      kind: 'procedural-placeholder',
      visualId: 'warpfall-wilds',
      labelKey: 'background.goldrinWildsWarpfall.name',
    },
  ]),
  audioCues: freezeRecords([
    {
      id: 'failed-spells',
      kind: 'synth',
      waveform: 'sine',
      notes: freezeRecords([
        { frequency: 760, endFrequency: 430, durationMs: 120, gain: 0.045, gapMs: 55 },
        { frequency: 610, endFrequency: 290, durationMs: 150, gain: 0.04, gapMs: 70 },
        { frequency: 440, endFrequency: 170, durationMs: 190, gain: 0.035, gapMs: 0 },
      ]),
    },
    {
      id: 'creature-roar',
      kind: 'synth',
      waveform: 'sawtooth',
      notes: freezeRecords([
        { frequency: 125, endFrequency: 58, durationMs: 720, gain: 0.055, gapMs: 0 },
      ]),
    },
  ]),
  scenes: freezeRecords([
    {
      id: WISHFIRE_WARP_CROSSING_SCENE_ID,
      backgroundId: 'wishfire-goldrin-wilds-warpfall',
      combatHandoffStepId: 'warp-017',
      presentation: Object.freeze({
        mode: 'conversation',
        viewport: 'mobile-first',
        shotSchemaVersion: 2,
        items: freezeRecords([
          { id: 'four-colorful-orbs', visualRef: 'procedural:four-colorful-orbs', width: 250, height: 150 },
          { id: 'red-orbs', visualRef: 'procedural:red-orbs', width: 250, height: 150 },
          { id: 'paper-map', visualRef: 'procedural:paper-map', width: 245, height: 170 },
        ]),
        cameraShots: freezeRecords([
          {
            id: 'hondo-fara-pair',
            kind: 'characters',
            compositionId: 'warp-crossing-party',
            cast: freezeRecords([
              { characterId: 'hondo', slot: 'left' },
              { characterId: 'fara', slot: 'right' },
            ]),
          },
          {
            id: 'kaja-runa-pair',
            kind: 'characters',
            compositionId: 'warp-crossing-party',
            reverseOf: 'hondo-fara-pair',
            cast: freezeRecords([
              { characterId: 'kaja', slot: 'left' },
              { characterId: 'runa', slot: 'right' },
            ]),
          },
          { id: 'four-orbs-focus', kind: 'item', item: Object.freeze({ itemId: 'four-colorful-orbs' }) },
          { id: 'red-orbs-tutorial', kind: 'item', item: Object.freeze({ itemId: 'red-orbs' }) },
          { id: 'paper-map-focus', kind: 'item', item: Object.freeze({ itemId: 'paper-map' }) },
          { id: 'creature-roar', kind: 'background-only' },
          { id: 'dark-ellipsis', kind: 'dark' },
        ]),
      }),
      steps: Object.freeze([
        line('warp-001', 'hondo', 'scene.warpCrossing.001', 'hondo-fara-pair'),
        line('warp-002', 'fara', 'scene.warpCrossing.002', 'hondo-fara-pair'),
        line('warp-003', 'kaja', 'scene.warpCrossing.003', 'kaja-runa-pair'),
        line('warp-004', 'runa', 'scene.warpCrossing.004', 'kaja-runa-pair'),
        line('warp-005', null, 'scene.warpCrossing.ellipsis', 'dark-ellipsis'),
        line('warp-006', 'hondo', 'scene.warpCrossing.006', 'hondo-fara-pair'),
        line('warp-007', 'runa', 'scene.warpCrossing.007', 'kaja-runa-pair'),
        line('warp-008', 'fara', 'scene.warpCrossing.008', 'four-orbs-focus'),
        line('warp-009', null, 'scene.warpCrossing.ellipsis', 'dark-ellipsis'),
        line('warp-010', 'runa', 'scene.warpCrossing.010', 'kaja-runa-pair'),
        line('warp-011', 'kaja', 'scene.warpCrossing.011', 'kaja-runa-pair', { audioCueId: 'failed-spells' }),
        line('warp-012', 'hondo', 'scene.warpCrossing.012', 'hondo-fara-pair'),
        line('warp-013', 'hondo', 'scene.warpCrossing.013', 'hondo-fara-pair'),
        line('warp-014', 'fara', 'scene.warpCrossing.014', 'hondo-fara-pair'),
        line('warp-015', null, 'scene.warpCrossing.ellipsis', 'dark-ellipsis'),
        line('warp-016', null, 'scene.warpCrossing.016', 'creature-roar', { audioCueId: 'creature-roar' }),
        line('warp-017', null, 'scene.warpCrossing.017', 'red-orbs-tutorial'),
        line('warp-018', 'kaja', 'scene.warpCrossing.018', 'kaja-runa-pair'),
        line('warp-019', 'hondo', 'scene.warpCrossing.019', 'hondo-fara-pair'),
        line('warp-020', 'fara', 'scene.warpCrossing.020', 'hondo-fara-pair'),
        line('warp-021', 'kaja', 'scene.warpCrossing.021', 'kaja-runa-pair'),
        line('warp-022', 'runa', 'scene.warpCrossing.022', 'kaja-runa-pair'),
        line('warp-023', 'hondo', 'scene.warpCrossing.023', 'hondo-fara-pair'),
        line('warp-023-runa', 'runa', 'scene.warpCrossing.023.runa', 'kaja-runa-pair'),
        line('warp-024', 'fara', 'scene.warpCrossing.024', 'hondo-fara-pair'),
        line('warp-025', 'runa', 'scene.warpCrossing.025', 'kaja-runa-pair'),
        line('warp-026', 'fara', 'scene.warpCrossing.026', 'hondo-fara-pair'),
        line('warp-027', 'kaja', 'scene.warpCrossing.027', 'kaja-runa-pair'),
        line('warp-028', 'runa', 'scene.warpCrossing.028', 'kaja-runa-pair'),
        line('warp-029', 'fara', 'scene.warpCrossing.029', 'paper-map-focus'),
        line('warp-030', 'fara', 'scene.warpCrossing.030', 'paper-map-focus'),
        line('warp-031', null, 'scene.warpCrossing.ellipsis', 'dark-ellipsis'),
        line('warp-032', 'kaja', 'scene.warpCrossing.032', 'kaja-runa-pair'),
        line('warp-033', 'fara', 'scene.warpCrossing.033', 'hondo-fara-pair'),
        line('warp-034', 'runa', 'scene.warpCrossing.034', 'kaja-runa-pair'),
        line('warp-035', 'hondo', 'scene.warpCrossing.035', 'hondo-fara-pair'),
      ]),
      onComplete: Object.freeze({
        type: 'scene-preview-complete',
        messageKey: 'scene.warpCrossing.complete',
      }),
    },
  ]),
  mapTriggers: freezeRecords([
    {
      id: 'map.wishfire-warp-crossing-arrival',
      layoutId: 'mapLayout',
      sceneId: WISHFIRE_WARP_CROSSING_SCENE_ID,
      coordinate: 'STORY-PREVIEW-01',
      once: false,
      labelKey: 'map.warpCrossing.label',
    },
  ]),
  locales: Object.freeze({
    en: Object.freeze({
      'character.hondo.name': 'Hondo',
      'character.fara.name': 'Fara',
      'character.kaja.name': 'Kaja',
      'character.runa.name': 'Runa',
      'background.goldrinWildsWarpfall.name': 'Goldrin Wilds',
      'map.warpCrossing.label': 'Story',
      'scene.warpCrossing.complete': 'End of Scene Preview',
      'scene.warpCrossing.ellipsis': '...',
      'scene.warpCrossing.001': 'What the...? What\u2019s the meaning of this?',
      'scene.warpCrossing.002': 'Speak up, you two. Who are you? What are you up to?',
      'scene.warpCrossing.003': 'Hey, we didn\u2019t do anything!',
      'scene.warpCrossing.004': 'Right, notice that we fell down hard too, you know!',
      'scene.warpCrossing.006': 'So, you two were warping south and wound up here just like us? That\u2019s odd. We were warping north. Never heard of warp tunnels crossing together like that.',
      'scene.warpCrossing.007': 'Right, we were headed to go investigate some ruins, but... come to think of it... where are we?',
      'scene.warpCrossing.008': 'And what are these weird orbs everywhere?',
      'scene.warpCrossing.010': 'I can\u2019t feel any magic... What is this place?',
      'scene.warpCrossing.011': 'Spells aren\u2019t doing anything.',
      'scene.warpCrossing.012': 'Same here... Nothing. Our magic is not answering...',
      'scene.warpCrossing.013': 'Hmmm... I wonder... Some years back, I heard a rumor about someone trying to crystallize magic, but that experiment was thousands of years ago...',
      'scene.warpCrossing.014': 'You think that\u2019s what these orbs are? But they\u2019re everywhere... Wait!... What\u2019s that!?',
      'scene.warpCrossing.016': 'RAWR!!',
      'scene.warpCrossing.017': 'COMBAT TUTORIAL: RED ORBS',
      'scene.warpCrossing.018': 'Hey, you two look like you\u2019ve seen things. What were those things?',
      'scene.warpCrossing.019': 'No idea, but we can cast during battle it seems.',
      'scene.warpCrossing.020': 'Good thing, too. These orbs helped us when we needed to fight...',
      'scene.warpCrossing.021': 'Yeah, that saved our skins!',
      'scene.warpCrossing.022': 'These orbs have a warmth when you hold them. Is that feeling the magic inside? Maybe that weird experiment worked.',
      'scene.warpCrossing.023': 'No, if they are a form of magic then we genies would have collected them. Ha! ...and you can bet merchants and bandits would have gathered them up to sell, too. No, this is unique somehow. But whatever magic they hold they were useful in a fight.',
      'scene.warpCrossing.023.runa': 'When I thought of what to do the orbs responded, but I couldn\u2019t feel magic like normal.',
      'scene.warpCrossing.024': 'Thank goodness they did something! Without magic we are just like humans. But let\u2019s think about this later. Now, we need to find some shelter and some answers.',
      'scene.warpCrossing.025': 'Kaja, where\u2019s that raggedy map you\u2019ve been working on? Maybe it can help.',
      'scene.warpCrossing.026': 'A map? How? Maps normally need magic to conjure up. Is this a trick?',
      'scene.warpCrossing.027': 'It\u2019s not a normal map. I made it myself.',
      'scene.warpCrossing.028': 'Right, so where are we?',
      'scene.warpCrossing.029': 'Let me take a look.',
      'scene.warpCrossing.030': 'Looks like we\u2019re in the Goldrin Wilds, but a lot of the map is empty. Guess you\u2019re pretty new to exploring, huh?',
      'scene.warpCrossing.032': 'Yeah, we\u2019ve only just started our expedition. Anyway, what\u2019s the plan? Where to?',
      'scene.warpCrossing.033': 'If what you\u2019re calling a map is correct, we need to head east. There should be a town near there. Let\u2019s go.',
      'scene.warpCrossing.034': 'Wait! We should grab some orbs to show the townsfolk.',
      'scene.warpCrossing.035': 'Good idea! Maybe someone there knows what\u2019s going on. And we can ask what these orbs are too.',
    }),
  }),
});
