export const state = {
  entities: [],
  globals: {
    // Core turn/combat flow
    TurnPhase: 0,
    TapIndex: 0,
    IsPlayerBusy: 0,
    IsAOEMatch: 0,
    CanPickGems: 1,
    CurrentTurnIndex: 0,
    LastMatchColor: -1,

    // Match/chain state
    matched: 0,
    MatchedColorValue: -1,
    ChainNumber: 0,
    ChainMultiplier: 1,
    ApplyChainToNextDamage: 0,
    ApplyChainToNextHeal: 0,
    SuppressChainUI: 0,
    ChainUIHideAt: 0,
    ChainUIDuration: 0,

    // Resources
    Player_Energy: 0,
    Player_maxEnergy: 150,
    goldTotal: 0,
    TokenWallet: {},
    LiveOpsProgress: {},

    // Party HP/buffs (totals mirror Construct globals)
    PartyHP: 0,
    PartyMaxHP: 0,
    PartyHPByIndex: [0, 0, 0, 0],
    PartyMaxHPByIndex: [0, 0, 0, 0],
    PartyBuff_ATK: 0,
    PartyBuff_DEF: 0,
    PartyBuff_MAG: 0,
    PartyBuff_RES: 0,
    PartyBuff_SPD: 0,
    PartyBuffCap_ATK: 20,
    PartyBuffCap_DEF: 20,
    PartyBuffCap_MAG: 20,
    PartyBuffCap_RES: 20,
    PartyBuffCap_SPD: 20,
    BuffExpire_ATK: 0,
    BuffExpire_DEF: 0,
    BuffExpire_MAG: 0,
    BuffExpire_RES: 0,
    BuffExpire_SPD: 0,
    BuffCasterUID_ATK: 0,
    BuffCasterUID_DEF: 0,
    BuffCasterUID_MAG: 0,
    BuffCasterUID_RES: 0,
    BuffCasterUID_SPD: 0,
    BuffTurns_ATK: 0,
    BuffTurns_DEF: 0,
    BuffTurns_MAG: 0,
    BuffTurns_RES: 0,
    BuffTurns_SPD: 0,
    BuffRollActive: 0,
    BuffRollEndsAt: 0,
    BuffRollFrame: 0,
    BuffRollSlot: 0,
    BuffRollType: 0,
    BuffRollSkillID: '',
    BuffRollActor: 0,
    BuffDurationDefault: 12,
    BuffProgActive: 0,
    BuffProgEndAt: 0,
    BuffProgSlot: 0,
    PendingSkillID: '',
    PendingActor: 0,
    SelectedEnemyUID: 0,
    ActorIntent: '',
    DebugMatchCount: 0,
    DebugTurnCount: 0,
    ActionInProgress: 0,
    ActionActorUID: 0,
    RoundActive: 0,
    RoundRoster: [],
    RoundGroups: [],
    RoundGroupIndex: 0,
    RoundMemberIndex: 0,
    PendingDeaths: {},
    RoundJitter: 0,
    UnisonTolerance: 0.5,
    SpeedDoubleRatio: 2.0,
    DamageTextDurationSec: 1.35,
    InitiativeMode: 'time',
    InitiativeThreshold: 100,
    InitiativeMeters: {},
    InitiativeCurrentUID: 0,
    InitiativePreviewSize: 6,
    InitiativeMaxLoops: 500,
    BattleStartRemaining: {},

    // Enemy/turn order arrays
    EnemyArray: [],
    EnemyIDs: [],
    EnemyKeyList: [],
    TurnOrderArray: [],
    TrackBuffs: [],
    BuffFrames: [-1, -1, -1, -1],
    GemRefillArray: [],
    EnemyData: [],
    NextUID: 1,

    // UI overlay state
    UIOverlay: 0,
    Locked: 0,
    PartyBuffUI: { atk: false, def: false, mag: false, res: false },
    PartyBuffSlots: [],
    BuffText: '',
    CombatActionLines: ['', '', '', ''],
    BlueBuffSequenceActive: 0,
    PowerAmpActive: 0,
    PowerAmpUID: 0,
    PowerAmpMultiplier: 1,
    PowerAmpConsumed: 0,
    PowerAmpByUID: {},
    PowerAmpPendingClearUID: 0,
    PowerAmpShownMultiplier: 1,
    PowerAmpVisualStartAt: 0,
    PowerAmpFadeUID: 0,
    PowerAmpFadeMultiplier: 1,
    PowerAmpFadeStartAt: 0,
    PowerAmpFadeDuration: 0.16,
    BoardFillActive: 0,
    PowerAmpVisualByUID: {},
    PowerAmpFadeByUID: {},
  },
};

export default state;
