#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {HERO_DEFINITIONS} from '../web-runner/src/core/heroDefinitions.mjs';import {computeCombatPower} from '../web-runner/src/core/combatPower.mjs';import {calculateDamageFromJs} from '../src/core/calculateDamageRules.mjs';import {resolveHeroSpeedMultiattack} from '../web-runner/src/core/dynamicInitiativeRules.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'output','balance');
const levels=[1,2,3,4,5,6,7,8,9,91,92,93,94,95,96,97,98,99], pairs=[[1,9],[9,1],[91,99],[99,91]];
const archetypes=[{id:'routine',tier:'routine',HP:45,ATK:3,DEF:4,MAG:3,RES:4,SPD:7},{id:'hard',tier:'hard',HP:62,ATK:4,DEF:5,MAG:4,RES:5,SPD:8},{id:'elite',tier:'elite',HP:85,ATK:5,DEF:7,MAG:5,RES:7,SPD:9},{id:'boss',tier:'boss',HP:130,ATK:6,DEF:9,MAG:6,RES:9,SPD:10}];
const n=v=>Number.isFinite(Number(v))?Number(v):0, ceil=v=>Math.max(1,Math.ceil(n(v)));
function stats(def,level){return Object.fromEntries(Object.entries(def.baseStats).map(([k,b])=>[k,Math.max(1,Math.floor(n(b)+n(def.growth[k])*(level-1)))]));}
function enemy(base,level){const scale=1+(level-1)*.12;return Object.fromEntries(Object.entries(base).map(([k,v])=>[k,['id','tier'].includes(k)?v:Math.max(1,Math.floor(n(v)*scale))]));}
function dmg(a,d,magic=false){return calculateDamageFromJs({power:magic?n(a.MAG):n(a.ATK),resist:magic?n(d.RES):n(d.DEF),roll01:.5,critRoll01:.5}).damage;}
function cp(stats,level,kit={}){return computeCombatPower({stats,currentLevel:level,kit});}
function roundDamage(a,d){return Math.max(dmg(a,d),dmg(a,d,true));}
function duel(hero,foe){let hh=n(hero.HP),eh=n(foe.HP),rounds=0,heroHits=0,enemyHits=0;while(hh>0&&eh>0&&rounds++<120){eh-=roundDamage(hero,foe);heroHits++;if(eh<=0)break;hh-=roundDamage(foe,hero);enemyHits++;}return {won:eh<=0&&hh>0,rounds,heroHits,enemyHits,heroHP:Math.max(0,hh),enemyHP:Math.max(0,eh)};}
function partyDuel(heroes,foe){const hp=heroes.map(hero=>n(hero.HP));let enemyHP=n(foe.HP),rounds=0;while(enemyHP>0&&hp.some(value=>value>0)&&rounds++<120){for(let i=0;i<heroes.length&&enemyHP>0;i++)if(hp[i]>0)enemyHP-=roundDamage(heroes[i],foe);if(enemyHP<=0)break;const target=hp.findIndex(value=>value>0);hp[target]-=roundDamage(foe,heroes[target]);}return {won:enemyHP<=0&&hp.some(value=>value>0),rounds,casualties:hp.filter(value=>value<=0).length};}
const rows=[],checks=[],failures=[];
for(const level of levels){for(const def of Object.values(HERO_DEFINITIONS)){const s=stats(def,level);rows.push({id:def.name,kind:'hero',role:def.role,level,stats:s,baseCP:cp(s,level,{afValue:2,control:def.role==='Controller'?2:0,sustain:def.role.includes('Support')?2:0}),currentCP:cp(s,level)});}for(const base of archetypes){const s=enemy(base,level);rows.push({id:`${base.id}-${level}`,kind:'enemy',role:base.tier,level,stats:s,baseCP:cp(s,level),currentCP:cp(s,level)});}}
for(const level of levels){const heroes=rows.filter(r=>r.kind==='hero'&&r.level===level),enemies=rows.filter(r=>r.kind==='enemy'&&r.level===level);for(const h of heroes)for(const e of enemies)for(const magic of [false,true])checks.push({surface:'same-level',level,hero:h.id,enemy:e.id,path:magic?'magic':'physical',heroDamage:dmg(h.stats,e.stats,magic),enemyDamage:dmg(e.stats,h.stats,magic),duel:duel(h.stats,e.stats)});}
for(const [heroLevel,enemyLevel] of pairs)for(const def of Object.values(HERO_DEFINITIONS))for(const base of archetypes)for(const magic of [false,true]){const h=stats(def,heroLevel),e=enemy(base,enemyLevel);checks.push({surface:'cross-level',heroLevel,enemyLevel,hero:def.name,enemy:base.id,path:magic?'magic':'physical',heroDamage:dmg(h,e,magic),enemyDamage:dmg(e,h,magic),duel:duel(h,e)});}
for(const check of checks){if(check.surface==='same-level'&&check.level===1&&check.heroDamage>9)failures.push(`L1 hero ${check.hero} ${check.path} damage ${check.heroDamage}`);if(check.surface==='same-level'&&check.level===1&&check.enemy==='routine-1'&&check.enemyDamage>ceil((check.duel.heroHP+check.enemyDamage)*.05))failures.push(`L1 routine burst ${check.hero}/${check.path} ${check.enemyDamage}`);}
for(const def of Object.values(HERO_DEFINITIONS)){const series=rows.filter(r=>r.kind==='hero'&&r.id===def.name).sort((a,b)=>a.level-b.level);for(let i=1;i<series.length;i++)if(series[i].baseCP<series[i-1].baseCP)failures.push(`CP inversion ${def.name} ${series[i-1].level}-${series[i].level}`);}
// Defense must lower an otherwise identical attack, and 2x Speed yields exactly one linked hit.
for(const level of [1,9,91,99]){const h=stats(HERO_DEFINITIONS.Huun,level),soft={...h,DEF:1,RES:1},hard={...h,DEF:h.DEF+20,RES:h.RES+20};if(dmg(h,hard)<dmg(h,soft)||dmg(hard,h)>dmg(soft,h)){}else failures.push(`defense relevance L${level}`);const foe={uid:99,kind:'enemy',hp:1,effectiveSpeed:10};const speedHero={uid:1,kind:'hero',hp:1,effectiveSpeed:20};if(!resolveHeroSpeedMultiattack({hero:speedHero,enemies:[foe]})||resolveHeroSpeedMultiattack({hero:speedHero,enemies:[foe],alreadyLinked:true})||resolveHeroSpeedMultiattack({hero:{...speedHero,effectiveSpeed:19},enemies:[foe]}))failures.push(`speed breakpoint L${level}`);}
const tierBands={routine:[.9,1],hard:[.75,1],elite:[.55,1],boss:[.4,1]};
for(const level of [1,9,91,99])for(const base of archetypes){const wins=partyDuel(Object.values(HERO_DEFINITIONS).map(def=>stats(def,level)),enemy(base,level)).won?1:0;const [min,max]=tierBands[base.tier];checks.push({surface:'win-rate-band',level,tier:base.tier,wins});if(wins<min||wins>max)failures.push(`win band L${level} ${base.tier}=${wins}`);}
const linkedBurst=Object.values(HERO_DEFINITIONS).map(def=>{const h=stats(def,9),e=enemy(archetypes[0],9),hit=roundDamage(h,e);return {hero:def.name,hit,linkedBurst:hit*2};});if(linkedBurst.some(row=>row.linkedBurst!==row.hit*2))failures.push('linked burst accounting');
const report={levels,pairs,rows,checks,linkedBurst,failures,pass:!failures.length,generatedAt:new Date().toISOString()};fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'cp-report.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'cp-report.csv'),'id,kind,role,level,baseCP,currentCP\n'+rows.map(r=>[r.id,r.kind,r.role,r.level,r.baseCP,r.currentCP].join(',')).join('\n')+'\n');fs.writeFileSync(path.join(out,'scaling-drift.json'),JSON.stringify({levels,pairs,checks,linkedBurst,failures},null,2)+'\n');fs.writeFileSync(path.join(out,'scaling-drift.md'),`# CP scaling drift\n\n${failures.length?'FAIL\n'+failures.map(v=>`- ${v}`).join('\n'):'PASS'}\n`);if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}else console.log(`PASS ${rows.length} CP rows, ${checks.length} bidirectional checks`);
