#!/usr/bin/env node
const http = require('http');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const args = process.argv.slice(2);
let port = 8080;
let host = '127.0.0.1';
for(let i=0;i<args.length;i++) if(args[i]==='--port' && args[i+1]) port = +args[i+1];
for(let i=0;i<args.length;i++) if(args[i]==='--host' && args[i+1]) host = String(args[i+1]);
const root = process.cwd();
const mime = {
  '.html':'text/html',
  '.js':'application/javascript',
  '.mjs':'application/javascript',
  '.json':'application/json',
  '.wasm':'application/wasm',
  '.css':'text/css',
  '.md':'text/markdown',
  '.png':'image/png',
  '.jpg':'image/jpeg',
  '.svg':'image/svg+xml',
};

function safeGit(args, fallback = '') {
  try {
    return String(execFileSync('git', args, { cwd: root, encoding: 'utf8' })).trim();
  } catch {
    return fallback;
  }
}

function safeExec(bin, args, fallback = '') {
  try {
    return String(execFileSync(bin, args, { cwd: root, encoding: 'utf8' })).trim();
  } catch {
    return fallback;
  }
}

function detectWorktreeName(gitDir, repoRoot) {
  if (!gitDir) return path.basename(repoRoot);
  const normalized = gitDir.replace(/\\/g, '/');
  const marker = '/worktrees/';
  const idx = normalized.lastIndexOf(marker);
  if (idx >= 0) {
    const tail = normalized.slice(idx + marker.length);
    const candidate = tail.split('/')[0];
    if (candidate) return candidate;
  }
  return path.basename(repoRoot);
}

function detectIssueId(branch) {
  const rawList = safeExec('bd', ['list', '--json'], '');
  if (rawList) {
    try {
      const issues = JSON.parse(rawList);
      if (Array.isArray(issues)) {
        const active = issues
          .filter((i) => i && i.status === 'in_progress' && typeof i.id === 'string')
          .sort((a, b) => String(b.updated_at || '').localeCompare(String(a.updated_at || '')));
        if (active.length) return active[0].id;
      }
    } catch {}
  }
  const fromBranch = String(branch || '').match(/(ORKA-[A-Za-z0-9]+)/i);
  if (fromBranch && fromBranch[1]) return fromBranch[1];
  const subjects = safeGit(['log', '-20', '--pretty=%s'], '');
  const fromHistory = String(subjects).match(/(?:bd-)?(ORKA-[A-Za-z0-9]+)/i);
  if (fromHistory && fromHistory[1]) return fromHistory[1];
  return 'ORKA-UNKNOWN';
}

function detectContracts(repoRoot) {
  const read = (rel) => {
    try {
      return fs.readFileSync(path.join(repoRoot, rel), 'utf8');
    } catch {
      return '';
    }
  };
  const stateJs = read('web-runner/modules/state.js');
  const fnBank = read('web-runner/modules/functionBank.js');
  const hasAstralWalletState = /\bAstralFlowWallet\b/.test(stateJs);
  const hasApplyStatGate = /\bBuffRollApplyStat\b/.test(fnBank);
  const hasBlueWalletWrite = /\bAstralFlowWallet\b/.test(fnBank);
  const orka69rReady = hasAstralWalletState && hasApplyStatGate && hasBlueWalletWrite;
  return {
    ORKA69R_READY: orka69rReady,
    checks: {
      hasAstralWalletState,
      hasApplyStatGate,
      hasBlueWalletWrite,
    },
  };
}

function writeRuntimeFingerprint() {
  const branch = safeGit(['rev-parse', '--abbrev-ref', 'HEAD'], 'unknown-branch');
  const gitDir = safeGit(['rev-parse', '--git-dir'], '');
  const worktree = detectWorktreeName(gitDir, root);
  const issueId = detectIssueId(branch);
  const contracts = detectContracts(root);
  const payload = {
    worktree,
    branch,
    issueId,
    contracts,
    generatedAt: new Date().toISOString(),
  };
  const body =
    '// Auto-generated by tools/serve_web.js at server start.\n' +
    `window.__ORKA_RUNTIME_FINGERPRINT__ = ${JSON.stringify(payload, null, 2)};\n`;
  const outPath = path.join(root, 'web-runner', 'runtime-fingerprint.js');
  fs.writeFileSync(outPath, body, 'utf8');
  console.log(
    `[FINGERPRINT] worktree=${worktree} branch=${branch} issue=${issueId} ORKA69R_READY=${contracts.ORKA69R_READY}`
  );
}

writeRuntimeFingerprint();

const server = http.createServer((req,res)=>{
  let url = decodeURIComponent(req.url.split('?')[0]);
  if(url === '/') {
    res.statusCode = 302;
    res.setHeader('Location', '/web-runner/index.html');
    res.end();
    return;
  }
  const fp = path.normalize(path.join(root, url));
  if(!fp.startsWith(root)) { res.statusCode = 403; res.end('Forbidden'); return; }
  fs.stat(fp, (err,st)=>{
    if(err){ res.statusCode=404; res.end('Not found'); return; }
    if(st.isDirectory()){ res.statusCode=301; res.setHeader('Location','/web-runner/index.html'); res.end(); return; }
    const ext = path.extname(fp);
    const ct = mime[ext] || 'application/octet-stream';
    res.setHeader('Content-Type', ct + (ct.startsWith('text/')?'; charset=utf-8':''));
    fs.createReadStream(fp).pipe(res);
  });
});
server.listen(port, host, ()=>console.log('Serving', root, 'on http://' + host + ':' + port));
